package com.pos.hibernate.beans;
// Generated Oct 8, 2017 11:43:55 AM by Hibernate Tools 5.2.5.Final


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Battery generated by hbm2java
 */
@Entity
@Table(name="battery"
    ,catalog="pos"
)
public class Battery  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -4823971992488406115L;
	private Integer id;
     private Tax tax;
     private String brandName;
     private String itemName;
     private BigDecimal mrpPrice;
     private String specs;
     private byte[] pic;
     private Set<Sales> saleses = new HashSet<Sales>(0);
     private Set<Inventory> inventories = new HashSet<Inventory>(0);

    public Battery() {
    }

	
    public Battery(Tax tax, String brandName, String itemName, BigDecimal mrpPrice, String specs) {
        this.tax = tax;
        this.brandName = brandName;
        this.itemName = itemName;
        this.mrpPrice = mrpPrice;
        this.specs = specs;
    }
    public Battery(Tax tax, String brandName, String itemName, BigDecimal mrpPrice, String specs, byte[] pic, Set<Sales> saleses, Set<Inventory> inventories) {
       this.tax = tax;
       this.brandName = brandName;
       this.itemName = itemName;
       this.mrpPrice = mrpPrice;
       this.specs = specs;
       this.pic = pic;
       this.saleses = saleses;
       this.inventories = inventories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tax", nullable=false)
    public Tax getTax() {
        return this.tax;
    }
    
    public void setTax(Tax tax) {
        this.tax = tax;
    }

    
    @Column(name="brand_name", nullable=false, length=50)
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    
    @Column(name="item_name", nullable=false, length=50)
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    
    @Column(name="mrp_price", nullable=false, precision=7)
    public BigDecimal getMrpPrice() {
        return this.mrpPrice;
    }
    
    public void setMrpPrice(BigDecimal mrpPrice) {
        this.mrpPrice = mrpPrice;
    }

    
    @Column(name="specs", nullable=false, length=150)
    public String getSpecs() {
        return this.specs;
    }
    
    public void setSpecs(String specs) {
        this.specs = specs;
    }

    
    @Column(name="pic")
    public byte[] getPic() {
        return this.pic;
    }
    
    public void setPic(byte[] pic) {
        this.pic = pic;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="battery")
    public Set<Sales> getSaleses() {
        return this.saleses;
    }
    
    public void setSaleses(Set<Sales> saleses) {
        this.saleses = saleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="battery")
    public Set<Inventory> getInventories() {
        return this.inventories;
    }
    
    public void setInventories(Set<Inventory> inventories) {
        this.inventories = inventories;
    }




}


