package com.pos.hibernate.beans;
// Generated Oct 8, 2017 11:43:55 AM by Hibernate Tools 5.2.5.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name="invoice"
    ,catalog="pos"
)
public class Invoice  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -4208236748839029788L;
	private Integer id;
     private Sales sales;
     private User user;
     private String billStatus;
     private BigDecimal price;
     private BigDecimal discount;
     private String customerName;
     private Date dateOfSale;
     private String taxApplied;

    public Invoice() {
    }

	
    public Invoice(Sales sales, User user, String billStatus, BigDecimal price, BigDecimal discount, String customerName) {
        this.sales = sales;
        this.user = user;
        this.billStatus = billStatus;
        this.price = price;
        this.discount = discount;
        this.customerName = customerName;
    }
    public Invoice(Sales sales, User user, String billStatus, BigDecimal price, BigDecimal discount, String customerName, Date dateOfSale, String taxApplied) {
       this.sales = sales;
       this.user = user;
       this.billStatus = billStatus;
       this.price = price;
       this.discount = discount;
       this.customerName = customerName;
       this.dateOfSale = dateOfSale;
       this.taxApplied = taxApplied;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sales", nullable=false)
    public Sales getSales() {
        return this.sales;
    }
    
    public void setSales(Sales sales) {
        this.sales = sales;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="biller", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="bill_status", nullable=false, length=20)
    public String getBillStatus() {
        return this.billStatus;
    }
    
    public void setBillStatus(String billStatus) {
        this.billStatus = billStatus;
    }

    
    @Column(name="price", nullable=false, precision=7)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="discount", nullable=false, precision=7)
    public BigDecimal getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    
    @Column(name="customer_name", nullable=false, length=100)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_of_sale", length=19)
    public Date getDateOfSale() {
        return this.dateOfSale;
    }
    
    public void setDateOfSale(Date dateOfSale) {
        this.dateOfSale = dateOfSale;
    }

    
    @Column(name="tax_applied", length=50)
    public String getTaxApplied() {
        return this.taxApplied;
    }
    
    public void setTaxApplied(String taxApplied) {
        this.taxApplied = taxApplied;
    }




}


