package com.pos.hibernate.beans;
// Generated Oct 8, 2017 11:43:55 AM by Hibernate Tools 5.2.5.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Purchase generated by hbm2java
 */
@Entity
@Table(name="purchase"
    ,catalog="pos"
)
public class Purchase  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 2444948331350192847L;
	private Integer id;
     private Inventory inventory;
     private String supplierName;
     private Date dateOfPurchase;
     private BigDecimal amount;

    public Purchase() {
    }

    public Purchase(Inventory inventory, String supplierName, Date dateOfPurchase, BigDecimal amount) {
       this.inventory = inventory;
       this.supplierName = supplierName;
       this.dateOfPurchase = dateOfPurchase;
       this.amount = amount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="inventory", nullable=false)
    public Inventory getInventory() {
        return this.inventory;
    }
    
    public void setInventory(Inventory inventory) {
        this.inventory = inventory;
    }

    
    @Column(name="supplier_name", nullable=false, length=100)
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_of_purchase", nullable=false, length=19)
    public Date getDateOfPurchase() {
        return this.dateOfPurchase;
    }
    
    public void setDateOfPurchase(Date dateOfPurchase) {
        this.dateOfPurchase = dateOfPurchase;
    }

    
    @Column(name="amount", nullable=false, precision=7)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }




}


