package com.pos.hibernate.beans;
// Generated Oct 8, 2017 11:43:55 AM by Hibernate Tools 5.2.5.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sales generated by hbm2java
 */
@Entity
@Table(name="sales"
    ,catalog="pos"
)
public class Sales  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1514590444842186097L;
	private Integer id;
     private Battery battery;
     private int invoice;
     private String serialNo;
     private Set<Invoice> invoices = new HashSet<Invoice>(0);

    public Sales() {
    }

	
    public Sales(Battery battery, int invoice, String serialNo) {
        this.battery = battery;
        this.invoice = invoice;
        this.serialNo = serialNo;
    }
    public Sales(Battery battery, int invoice, String serialNo, Set<Invoice> invoices) {
       this.battery = battery;
       this.invoice = invoice;
       this.serialNo = serialNo;
       this.invoices = invoices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="battery", nullable=false)
    public Battery getBattery() {
        return this.battery;
    }
    
    public void setBattery(Battery battery) {
        this.battery = battery;
    }

    
    @Column(name="invoice", nullable=false)
    public int getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(int invoice) {
        this.invoice = invoice;
    }

    
    @Column(name="serial_no", nullable=false, length=100)
    public String getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sales")
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


