package com.pos.hibernate.beans;
// Generated Oct 8, 2017 11:43:55 AM by Hibernate Tools 5.2.5.Final


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tax generated by hbm2java
 */
@Entity
@Table(name="tax"
    ,catalog="pos"
    , uniqueConstraints = @UniqueConstraint(columnNames="hsn_code") 
)
public class Tax  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -7700659044773242608L;
	private Integer id;
     private String batteryType;
     private int hsnCode;
     private BigDecimal cgst;
     private BigDecimal sgst;
     private BigDecimal igst;
     private Set<Battery> batteries = new HashSet<Battery>(0);

    public Tax() {
    }

	
    public Tax(String batteryType, int hsnCode, BigDecimal cgst, BigDecimal sgst, BigDecimal igst) {
        this.batteryType = batteryType;
        this.hsnCode = hsnCode;
        this.cgst = cgst;
        this.sgst = sgst;
        this.igst = igst;
    }
    public Tax(String batteryType, int hsnCode, BigDecimal cgst, BigDecimal sgst, BigDecimal igst, Set<Battery> batteries) {
       this.batteryType = batteryType;
       this.hsnCode = hsnCode;
       this.cgst = cgst;
       this.sgst = sgst;
       this.igst = igst;
       this.batteries = batteries;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="battery_type", nullable=false, length=50)
    public String getBatteryType() {
        return this.batteryType;
    }
    
    public void setBatteryType(String batteryType) {
        this.batteryType = batteryType;
    }

    
    @Column(name="hsn_code", unique=true, nullable=false)
    public int getHsnCode() {
        return this.hsnCode;
    }
    
    public void setHsnCode(int hsnCode) {
        this.hsnCode = hsnCode;
    }

    
    @Column(name="cgst", nullable=false, precision=2)
    public BigDecimal getCgst() {
        return this.cgst;
    }
    
    public void setCgst(BigDecimal cgst) {
        this.cgst = cgst;
    }

    
    @Column(name="sgst", nullable=false, precision=2)
    public BigDecimal getSgst() {
        return this.sgst;
    }
    
    public void setSgst(BigDecimal sgst) {
        this.sgst = sgst;
    }

    
    @Column(name="igst", nullable=false, precision=2)
    public BigDecimal getIgst() {
        return this.igst;
    }
    
    public void setIgst(BigDecimal igst) {
        this.igst = igst;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tax")
    public Set<Battery> getBatteries() {
        return this.batteries;
    }
    
    public void setBatteries(Set<Battery> batteries) {
        this.batteries = batteries;
    }




}


