package com.pos.hibernate.beans;
// Generated Oct 8, 2017 11:43:55 AM by Hibernate Tools 5.2.5.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="pos"
)
public class User  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1860541355576079381L;
	private Integer id;
     private String name;
     private String pswd;
     private long permissions;
     private Set<Invoice> invoices = new HashSet<Invoice>(0);

    public User() {
    }

	
    public User(String name, String pswd, long permissions) {
        this.name = name;
        this.pswd = pswd;
        this.permissions = permissions;
    }
    public User(String name, String pswd, long permissions, Set<Invoice> invoices) {
       this.name = name;
       this.pswd = pswd;
       this.permissions = permissions;
       this.invoices = invoices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="pswd", nullable=false, length=100)
    public String getPswd() {
        return this.pswd;
    }
    
    public void setPswd(String pswd) {
        this.pswd = pswd;
    }

    
    @Column(name="permissions", nullable=false)
    public long getPermissions() {
        return this.permissions;
    }
    
    public void setPermissions(long permissions) {
        this.permissions = permissions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


